<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KAI-DT136" name="Default test" tests="1" failures="0" timestamp="17 May 2016 05:46:07 GMT" time="6.875" errors="0">
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.SchoolOfDragons.LiveMembershipPageChecks.TestCase2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.Report.terminate(Report.java:412)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:708)
	at com.SchoolOfDragons.LiveMembershipPageChecks.TestCase2.tearDown(TestCase2.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="@AfterTest printReportPath" time="0.0" classname="com.SchoolOfDragons.LiveMembershipPageChecks.TestCase2">
    <skipped/>
  </testcase> <!-- @AfterTest printReportPath -->
  <testcase name="ValidAuthorisedPlayerLogin" time="0.0" classname="com.SchoolOfDragons.LiveMembershipPageChecks.TestCase2">
    <skipped/>
  </testcase> <!-- ValidAuthorisedPlayerLogin -->
</testsuite> <!-- Default test -->
